name: Generate static org-roam-ui page
on:
  push:
    branches:
      - main
jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/org-roam-ui-hosting@main
        with:
          org-roam-db-filename: org-roam.db
          deploy-to-pages: true
          site-title: my org-roam!
